import { Router } from 'express';
import { employeeController } from '../controllers/employee.controller.js';
import { employeeRepository } from '../repositories/employee.repository.js';
import { protect, protectEmployee, restrictTo } from '../middlewares/auth.middleware.js';
import { employeeUpload } from '../middlewares/upload.middleware.js';
const router = Router();
router.post('/login', employeeController.login);
router.get('/me', protectEmployee, employeeController.profile);
router.post('/me/password', protectEmployee, employeeController.changePassword);
router.post('/me/picture', protectEmployee, employeeUpload.single('profilePicture'), employeeController.updatePicture);
router.get('/me/attendance', protectEmployee, employeeController.attendance);
router.get('/me/payroll', protectEmployee, employeeController.payroll);
router.get('/me/attendance/export', protectEmployee, employeeController.exportAttendance);
router.use(protect, restrictTo('superadmin', 'editor'));
router.get('/next-id', employeeController.nextId);
router.get('/', employeeController.list);
router.post('/', employeeUpload.fields([{ name: 'profilePicture', maxCount: 1 }, { name: 'idProof', maxCount: 1 }]), employeeController.create);
router.put('/:id', employeeUpload.fields([{ name: 'profilePicture', maxCount: 1 }, { name: 'idProof', maxCount: 1 }]), employeeController.update);
router.post('/:id/reset-password', employeeController.resetPassword);
router.get('/:id', employeeController.detail);
router.get('/:id/attendance', async (req, res, next) => { try { res.ok(await employeeRepository.attendance(req.params.id)); } catch (e) { next(e); } });
router.get('/:id/payroll', employeeController.payroll);
router.get('/:id/attendance/export', employeeController.exportAttendance);
router.post('/attendance', employeeController.markAttendance);
router.put('/attendance', employeeController.markAttendance);
router.get('/:id/id-proof', restrictTo('superadmin'), employeeController.idProof);
router.delete('/:id', restrictTo('superadmin'), employeeController.remove);
export default router;