import React, { useState } from 'react';
import { Navigate, useNavigate } from 'react-router-dom';
import { LogIn, ShieldCheck } from 'lucide-react';
import { useEmployeeAuth } from '../../context/EmployeeAuthContext';
export default function EmployeeLogin() {
  const { login, isAuthenticated } = useEmployeeAuth(); const navigate = useNavigate(); const [employeeId,setEmployeeId]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  if (isAuthenticated) return <Navigate to="/employee" replace />;
  const submit = async (e) => { e.preventDefault(); setLoading(true); setError(''); try { await login(employeeId,password); navigate('/employee'); } catch (err) { setError(err.message || 'Unable to sign in.'); } finally { setLoading(false); } };
  return <main className="flex min-h-screen items-center justify-center bg-slate-950 px-4 text-slate-100"><form onSubmit={submit} className="w-full max-w-md rounded-2xl border border-slate-800 bg-slate-900 p-8 shadow-2xl"><ShieldCheck className="mb-5 h-10 w-10 text-cyan-400" /><h1 className="text-2xl font-bold">Employee Login</h1><p className="mt-2 text-sm text-slate-400">Access your ERV profile and attendance.</p>{error && <div className="mt-4 rounded-lg border border-rose-500/30 bg-rose-500/10 p-3 text-sm text-rose-300">{error}</div>}<label className="mt-6 block text-sm text-slate-300">Employee ID<input required value={employeeId} onChange={e=>setEmployeeId(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 outline-none focus:border-cyan-400" /></label><label className="mt-4 block text-sm text-slate-300">Password<input required type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 outline-none focus:border-cyan-400" /></label><button disabled={loading} className="mt-6 flex w-full cursor-pointer items-center justify-center gap-2 rounded-xl bg-cyan-500 px-4 py-3 font-semibold text-slate-950 disabled:opacity-60"><LogIn className="h-4 w-4" />{loading?'Signing in...':'Sign in'}</button></form></main>;
}